#pragma once
namespace nce {
    enum class KeyStates : uint8_t {
        pressed,
        released
    };
    enum class KeyCode : uint32_t {
        NoSymbol                       = 0x000000,  /* Special KeySym */
        VoidSymbol                     = 0xffffff,  /* Void symbol */
        BackSpace                      = 0xff08,  /* U+0008 BACKSPACE */
        Tab                            = 0xff09,  /* U+0009 CHARACTER TABULATION */
        Linefeed                       = 0xff0a,  /* U+000A LINE FEED */
        Clear                          = 0xff0b,  /* U+000B LINE TABULATION */
        Return                         = 0xff0d,  /* U+000D CARRIAGE RETURN */
        Pause                          = 0xff13,  /* Pause, hold */
        Scroll_Lock                    = 0xff14,
        Sys_Req                        = 0xff15,
        Escape                         = 0xff1b,  /* U+001B ESCAPE */
        Delete                         = 0xffff,  /* U+007F DELETE */
        Multi_key                      = 0xff20,  /* Multi-key character compose */
        Codeinput                      = 0xff37,
        SingleCandidate                = 0xff3c,
        MultipleCandidate              = 0xff3d,
        PreviousCandidate              = 0xff3e,
        Kanji                          = 0xff21,  /* Kanji, Kanji convert */
        Muhenkan                       = 0xff22,  /* Cancel Conversion */
        Henkan_Mode                    = 0xff23,  /* Start/Stop Conversion */
        Henkan                         = 0xff23,  /* Alias for Henkan_Mode */
        Romaji                         = 0xff24,  /* to Romaji */
        Hiragana                       = 0xff25,  /* to Hiragana */
        Katakana                       = 0xff26,  /* to Katakana */
        Hiragana_Katakana              = 0xff27,  /* Hiragana/Katakana toggle */
        Zenkaku                        = 0xff28,  /* to Zenkaku */
        Hankaku                        = 0xff29,  /* to Hankaku */
        Zenkaku_Hankaku                = 0xff2a,  /* Zenkaku/Hankaku toggle */
        Touroku                        = 0xff2b,  /* Add to Dictionary */
        Massyo                         = 0xff2c,  /* Delete from Dictionary */
        Kana_Lock                      = 0xff2d,  /* Kana Lock */
        Kana_Shift                     = 0xff2e,  /* Kana Shift */
        Eisu_Shift                     = 0xff2f,  /* Alphanumeric Shift */
        Eisu_toggle                    = 0xff30,  /* Alphanumeric toggle */
        Kanji_Bangou                   = 0xff37,  /* Codeinput */
        Zen_Koho                       = 0xff3d,  /* Multiple/All Candidate(s) */
        Mae_Koho                       = 0xff3e,  /* Previous Candidate */
        Home                           = 0xff50,
        Left                           = 0xff51,  /* Move left, left arrow */
        Up                             = 0xff52,  /* Move up, up arrow */
        Right                          = 0xff53,  /* Move right, right arrow */
        Down                           = 0xff54,  /* Move down, down arrow */
        Prior                          = 0xff55,  /* Prior, previous */
        Page_Up                        = 0xff55,  /* deprecated alias for Prior */
        Next                           = 0xff56,  /* Next */
        Page_Down                      = 0xff56,  /* deprecated alias for Next */
        End                            = 0xff57,  /* EOL */
        Begin                          = 0xff58,  /* BOL */
        Select                         = 0xff60,  /* Select, mark */
        Print                          = 0xff61,
        Execute                        = 0xff62,  /* Execute, run, do */
        Insert                         = 0xff63,  /* Insert, insert here */
        Undo                           = 0xff65,
        Redo                           = 0xff66,  /* Redo, again */
        Menu                           = 0xff67,
        Find                           = 0xff68,  /* Find, search */
        Cancel                         = 0xff69,  /* Cancel, stop, abort, exit */
        Help                           = 0xff6a,  /* Help */
        Break                          = 0xff6b,
        Mode_switch                    = 0xff7e,  /* Character set switch */
        script_switch                  = 0xff7e,  /* Alias for Mode_switch */
        Num_Lock                       = 0xff7f,
        KP_Space                       = 0xff80,  /*<U+0020 SPACE>*/
        KP_Tab                         = 0xff89,  /*<U+0009 CHARACTER TABULATION>*/
        KP_Enter                       = 0xff8d,  /*<U+000D CARRIAGE RETURN>*/
        KP_F1                          = 0xff91,  /* PF1, KP_A, ... */
        KP_F2                          = 0xff92,
        KP_F3                          = 0xff93,
        KP_F4                          = 0xff94,
        KP_Home                        = 0xff95,
        KP_Left                        = 0xff96,
        KP_Up                          = 0xff97,
        KP_Right                       = 0xff98,
        KP_Down                        = 0xff99,
        KP_Prior                       = 0xff9a,
        KP_Page_Up                     = 0xff9a,  /* deprecated alias for KP_Prior */
        KP_Next                        = 0xff9b,
        KP_Page_Down                   = 0xff9b,  /* deprecated alias for KP_Next */
        KP_End                         = 0xff9c,
        KP_Begin                       = 0xff9d,
        KP_Insert                      = 0xff9e,
        KP_Delete                      = 0xff9f,
        KP_Equal                       = 0xffbd,  /*<U+003D EQUALS SIGN>*/
        KP_Multiply                    = 0xffaa,  /*<U+002A ASTERISK>*/
        KP_Add                         = 0xffab,  /*<U+002B PLUS SIGN>*/
        KP_Separator                   = 0xffac,  /*<U+002C COMMA>*/
        KP_Subtract                    = 0xffad,  /*<U+002D HYPHEN-MINUS>*/
        KP_Decimal                     = 0xffae,  /*<U+002E FULL STOP>*/
        KP_Divide                      = 0xffaf,  /*<U+002F SOLIDUS>*/
        KP_0                           = 0xffb0,  /*<U+0030 DIGIT ZERO>*/
        KP_1                           = 0xffb1,  /*<U+0031 DIGIT ONE>*/
        KP_2                           = 0xffb2,  /*<U+0032 DIGIT TWO>*/
        KP_3                           = 0xffb3,  /*<U+0033 DIGIT THREE>*/
        KP_4                           = 0xffb4,  /*<U+0034 DIGIT FOUR>*/
        KP_5                           = 0xffb5,  /*<U+0035 DIGIT FIVE>*/
        KP_6                           = 0xffb6,  /*<U+0036 DIGIT SIX>*/
        KP_7                           = 0xffb7,  /*<U+0037 DIGIT SEVEN>*/
        KP_8                           = 0xffb8,  /*<U+0038 DIGIT EIGHT>*/
        KP_9                           = 0xffb9,  /*<U+0039 DIGIT NINE>*/
        F1                             = 0xffbe,
        F2                             = 0xffbf,
        F3                             = 0xffc0,
        F4                             = 0xffc1,
        F5                             = 0xffc2,
        F6                             = 0xffc3,
        F7                             = 0xffc4,
        F8                             = 0xffc5,
        F9                             = 0xffc6,
        F10                            = 0xffc7,
        F11                            = 0xffc8,
        L1                             = 0xffc8,  /* deprecated alias for F11 */
        F12                            = 0xffc9,
        L2                             = 0xffc9,  /* deprecated alias for F12 */
        F13                            = 0xffca,
        L3                             = 0xffca,  /* deprecated alias for F13 */
        F14                            = 0xffcb,
        L4                             = 0xffcb,  /* deprecated alias for F14 */
        F15                            = 0xffcc,
        L5                             = 0xffcc,  /* deprecated alias for F15 */
        F16                            = 0xffcd,
        L6                             = 0xffcd,  /* deprecated alias for F16 */
        F17                            = 0xffce,
        L7                             = 0xffce,  /* deprecated alias for F17 */
        F18                            = 0xffcf,
        L8                             = 0xffcf,  /* deprecated alias for F18 */
        F19                            = 0xffd0,
        L9                             = 0xffd0,  /* deprecated alias for F19 */
        F20                            = 0xffd1,
        L10                            = 0xffd1,  /* deprecated alias for F20 */
        F21                            = 0xffd2,
        R1                             = 0xffd2,  /* deprecated alias for F21 */
        F22                            = 0xffd3,
        R2                             = 0xffd3,  /* deprecated alias for F22 */
        F23                            = 0xffd4,
        R3                             = 0xffd4,  /* deprecated alias for F23 */
        F24                            = 0xffd5,
        R4                             = 0xffd5,  /* deprecated alias for F24 */
        F25                            = 0xffd6,
        R5                             = 0xffd6,  /* deprecated alias for F25 */
        F26                            = 0xffd7,
        R6                             = 0xffd7,  /* deprecated alias for F26 */
        F27                            = 0xffd8,
        R7                             = 0xffd8,  /* deprecated alias for F27 */
        F28                            = 0xffd9,
        R8                             = 0xffd9,  /* deprecated alias for F28 */
        F29                            = 0xffda,
        R9                             = 0xffda,  /* deprecated alias for F29 */
        F30                            = 0xffdb,
        R10                            = 0xffdb,  /* deprecated alias for F30 */
        F31                            = 0xffdc,
        R11                            = 0xffdc,  /* deprecated alias for F31 */
        F32                            = 0xffdd,
        R12                            = 0xffdd,  /* deprecated alias for F32 */
        F33                            = 0xffde,
        R13                            = 0xffde,  /* deprecated alias for F33 */
        F34                            = 0xffdf,
        R14                            = 0xffdf,  /* deprecated alias for F34 */
        F35                            = 0xffe0,
        R15                            = 0xffe0,  /* deprecated alias for F35 */
        Shift_L                        = 0xffe1,  /* Left shift */
        Shift_R                        = 0xffe2,  /* Right shift */
        Control_L                      = 0xffe3,  /* Left control */
        Control_R                      = 0xffe4,  /* Right control */
        Caps_Lock                      = 0xffe5,  /* Caps lock */
        Shift_Lock                     = 0xffe6,  /* Shift lock */
        Meta_L                         = 0xffe7,  /* Left meta */
        Meta_R                         = 0xffe8,  /* Right meta */
        Alt_L                          = 0xffe9,  /* Left alt */
        Alt_R                          = 0xffea,  /* Right alt */
        Super_L                        = 0xffeb,  /* Left super */
        Super_R                        = 0xffec,  /* Right super */
        Hyper_L                        = 0xffed,  /* Left hyper */
        Hyper_R                        = 0xffee,  /* Right hyper */
        ISO_Lock                       = 0xfe01,
        ISO_Level2_Latch               = 0xfe02,
        ISO_Level3_Shift               = 0xfe03,
        ISO_Level3_Latch               = 0xfe04,
        ISO_Level3_Lock                = 0xfe05,
        ISO_Level5_Shift               = 0xfe11,
        ISO_Level5_Latch               = 0xfe12,
        ISO_Level5_Lock                = 0xfe13,
        ISO_Group_Shift                = 0xff7e,  /* Alias for Mode_switch */
        ISO_Group_Latch                = 0xfe06,
        ISO_Group_Lock                 = 0xfe07,
        ISO_Next_Group                 = 0xfe08,
        ISO_Next_Group_Lock            = 0xfe09,
        ISO_Prev_Group                 = 0xfe0a,
        ISO_Prev_Group_Lock            = 0xfe0b,
        ISO_First_Group                = 0xfe0c,
        ISO_First_Group_Lock           = 0xfe0d,
        ISO_Last_Group                 = 0xfe0e,
        ISO_Last_Group_Lock            = 0xfe0f,
        ISO_Left_Tab                   = 0xfe20,
        ISO_Move_Line_Up               = 0xfe21,
        ISO_Move_Line_Down             = 0xfe22,
        ISO_Partial_Line_Up            = 0xfe23,
        ISO_Partial_Line_Down          = 0xfe24,
        ISO_Partial_Space_Left         = 0xfe25,
        ISO_Partial_Space_Right        = 0xfe26,
        ISO_Set_Margin_Left            = 0xfe27,
        ISO_Set_Margin_Right           = 0xfe28,
        ISO_Release_Margin_Left        = 0xfe29,
        ISO_Release_Margin_Right       = 0xfe2a,
        ISO_Release_Both_Margins       = 0xfe2b,
        ISO_Fast_Cursor_Left           = 0xfe2c,
        ISO_Fast_Cursor_Right          = 0xfe2d,
        ISO_Fast_Cursor_Up             = 0xfe2e,
        ISO_Fast_Cursor_Down           = 0xfe2f,
        ISO_Continuous_Underline       = 0xfe30,
        ISO_Discontinuous_Underline    = 0xfe31,
        ISO_Emphasize                  = 0xfe32,
        ISO_Center_Object              = 0xfe33,
        ISO_Enter                      = 0xfe34,
        dead_grave                     = 0xfe50,
        dead_acute                     = 0xfe51,
        dead_circumflex                = 0xfe52,
        dead_tilde                     = 0xfe53,
        dead_perispomeni               = 0xfe53,  /* alias for dead_tilde */
        dead_macron                    = 0xfe54,
        dead_breve                     = 0xfe55,
        dead_abovedot                  = 0xfe56,
        dead_diaeresis                 = 0xfe57,
        dead_abovering                 = 0xfe58,
        dead_doubleacute               = 0xfe59,
        dead_caron                     = 0xfe5a,
        dead_cedilla                   = 0xfe5b,
        dead_ogonek                    = 0xfe5c,
        dead_iota                      = 0xfe5d,
        dead_voiced_sound              = 0xfe5e,
        dead_semivoiced_sound          = 0xfe5f,
        dead_belowdot                  = 0xfe60,
        dead_hook                      = 0xfe61,
        dead_horn                      = 0xfe62,
        dead_stroke                    = 0xfe63,
        dead_abovecomma                = 0xfe64,
        dead_psili                     = 0xfe64,  /* alias for dead_abovecomma */
        dead_abovereversedcomma        = 0xfe65,
        dead_dasia                     = 0xfe65,  /* alias for dead_abovereversedcomma */
        dead_doublegrave               = 0xfe66,
        dead_belowring                 = 0xfe67,
        dead_belowmacron               = 0xfe68,
        dead_belowcircumflex           = 0xfe69,
        dead_belowtilde                = 0xfe6a,
        dead_belowbreve                = 0xfe6b,
        dead_belowdiaeresis            = 0xfe6c,
        dead_invertedbreve             = 0xfe6d,
        dead_belowcomma                = 0xfe6e,
        dead_currency                  = 0xfe6f,
        dead_a                         = 0xfe80,
        dead_A                         = 0xfe81,
        dead_e                         = 0xfe82,
        dead_E                         = 0xfe83,
        dead_i                         = 0xfe84,
        dead_I                         = 0xfe85,
        dead_o                         = 0xfe86,
        dead_O                         = 0xfe87,
        dead_u                         = 0xfe88,
        dead_U                         = 0xfe89,
        dead_schwa                     = 0xfe8a,
        dead_SCHWA                     = 0xfe8b,
        dead_small_schwa               = 0xfe8a,  /* deprecated, remove in 2025 */
        dead_capital_schwa             = 0xfe8b,  /* deprecated, remove in 2025 */
        dead_greek                     = 0xfe8c,
        dead_hamza                     = 0xfe8d,
        First_Virtual_Screen           = 0xfed0,
        Prev_Virtual_Screen            = 0xfed1,
        Next_Virtual_Screen            = 0xfed2,
        Last_Virtual_Screen            = 0xfed4,
        Terminate_Server               = 0xfed5,
        AccessX_Enable                 = 0xfe70,
        AccessX_Feedback_Enable        = 0xfe71,
        RepeatKeys_Enable              = 0xfe72,
        SlowKeys_Enable                = 0xfe73,
        BounceKeys_Enable              = 0xfe74,
        StickyKeys_Enable              = 0xfe75,
        MouseKeys_Enable               = 0xfe76,
        MouseKeys_Accel_Enable         = 0xfe77,
        Overlay1_Enable                = 0xfe78,
        Overlay2_Enable                = 0xfe79,
        AudibleBell_Enable             = 0xfe7a,
        Pointer_Left                   = 0xfee0,
        Pointer_Right                  = 0xfee1,
        Pointer_Up                     = 0xfee2,
        Pointer_Down                   = 0xfee3,
        Pointer_UpLeft                 = 0xfee4,
        Pointer_UpRight                = 0xfee5,
        Pointer_DownLeft               = 0xfee6,
        Pointer_DownRight              = 0xfee7,
        Pointer_Button_Dflt            = 0xfee8,
        Pointer_Button1                = 0xfee9,
        Pointer_Button2                = 0xfeea,
        Pointer_Button3                = 0xfeeb,
        Pointer_Button4                = 0xfeec,
        Pointer_Button5                = 0xfeed,
        Pointer_DblClick_Dflt          = 0xfeee,
        Pointer_DblClick1              = 0xfeef,
        Pointer_DblClick2              = 0xfef0,
        Pointer_DblClick3              = 0xfef1,
        Pointer_DblClick4              = 0xfef2,
        Pointer_DblClick5              = 0xfef3,
        Pointer_Drag_Dflt              = 0xfef4,
        Pointer_Drag1                  = 0xfef5,
        Pointer_Drag2                  = 0xfef6,
        Pointer_Drag3                  = 0xfef7,
        Pointer_Drag4                  = 0xfef8,
        Pointer_Drag5                  = 0xfefd,
        Pointer_EnableKeys             = 0xfef9,
        Pointer_Accelerate             = 0xfefa,
        Pointer_DfltBtnNext            = 0xfefb,
        Pointer_DfltBtnPrev            = 0xfefc,
        ch                             = 0xfea0,
        Ch                             = 0xfea1,
        CH                             = 0xfea2,
        c_h                            = 0xfea3,
        C_h                            = 0xfea4,
        C_H                            = 0xfea5,
        s_3270_Duplicate                 = 0xfd01,
        s_3270_FieldMark                 = 0xfd02,
        s_3270_Right2                    = 0xfd03,
        s_3270_Left2                     = 0xfd04,
        s_3270_BackTab                   = 0xfd05,
        s_3270_EraseEOF                  = 0xfd06,
        s_3270_EraseInput                = 0xfd07,
        s_3270_Reset                     = 0xfd08,
        s_3270_Quit                      = 0xfd09,
        s_3270_PA1                       = 0xfd0a,
        s_3270_PA2                       = 0xfd0b,
        s_3270_PA3                       = 0xfd0c,
        s_3270_Test                      = 0xfd0d,
        s_3270_Attn                      = 0xfd0e,
        s_3270_CursorBlink               = 0xfd0f,
        s_3270_AltCursor                 = 0xfd10,
        s_3270_KeyClick                  = 0xfd11,
        s_3270_Jump                      = 0xfd12,
        s_3270_Ident                     = 0xfd13,
        s_3270_Rule                      = 0xfd14,
        s_3270_Copy                      = 0xfd15,
        s_3270_Play                      = 0xfd16,
        s_3270_Setup                     = 0xfd17,
        s_3270_Record                    = 0xfd18,
        s_3270_ChangeScreen              = 0xfd19,
        s_3270_DeleteWord                = 0xfd1a,
        s_3270_ExSelect                  = 0xfd1b,
        s_3270_CursorSelect              = 0xfd1c,
        s_3270_PrintScreen               = 0xfd1d,
        s_3270_Enter                     = 0xfd1e,
        space                          = 0x0020,  /* U+0020 SPACE */
        exclam                         = 0x0021,  /* U+0021 EXCLAMATION MARK */
        quotedbl                       = 0x0022,  /* U+0022 QUOTATION MARK */
        numbersign                     = 0x0023,  /* U+0023 NUMBER SIGN */
        dollar                         = 0x0024,  /* U+0024 DOLLAR SIGN */
        percent                        = 0x0025,  /* U+0025 PERCENT SIGN */
        ampersand                      = 0x0026,  /* U+0026 AMPERSAND */
        apostrophe                     = 0x0027,  /* U+0027 APOSTROPHE */
        quoteright                     = 0x0027,  /* deprecated */
        parenleft                      = 0x0028,  /* U+0028 LEFT PARENTHESIS */
        parenright                     = 0x0029,  /* U+0029 RIGHT PARENTHESIS */
        asterisk                       = 0x002a,  /* U+002A ASTERISK */
        plus                           = 0x002b,  /* U+002B PLUS SIGN */
        comma                          = 0x002c,  /* U+002C COMMA */
        minus                          = 0x002d,  /* U+002D HYPHEN-MINUS */
        period                         = 0x002e,  /* U+002E FULL STOP */
        slash                          = 0x002f,  /* U+002F SOLIDUS */
        zero                              = 0x0030,  /* U+0030 DIGIT ZERO */
        one                              = 0x0031,  /* U+0031 DIGIT ONE */
        two                              = 0x0032,  /* U+0032 DIGIT TWO */
        three                              = 0x0033,  /* U+0033 DIGIT THREE */
        four                              = 0x0034,  /* U+0034 DIGIT FOUR */
        five                              = 0x0035,  /* U+0035 DIGIT FIVE */
        six                              = 0x0036,  /* U+0036 DIGIT SIX */
        seven                              = 0x0037,  /* U+0037 DIGIT SEVEN */
        eight                              = 0x0038,  /* U+0038 DIGIT EIGHT */
        nine                              = 0x0039,  /* U+0039 DIGIT NINE */
        colon                          = 0x003a,  /* U+003A COLON */
        semicolon                      = 0x003b,  /* U+003B SEMICOLON */
        less                           = 0x003c,  /* U+003C LESS-THAN SIGN */
        equal                          = 0x003d,  /* U+003D EQUALS SIGN */
        greater                        = 0x003e,  /* U+003E GREATER-THAN SIGN */
        question                       = 0x003f,  /* U+003F QUESTION MARK */
        at                             = 0x0040,  /* U+0040 COMMERCIAL AT */
        A                              = 0x0041,  /* U+0041 LATIN CAPITAL LETTER A */
        B                              = 0x0042,  /* U+0042 LATIN CAPITAL LETTER B */
        C                              = 0x0043,  /* U+0043 LATIN CAPITAL LETTER C */
        D                              = 0x0044,  /* U+0044 LATIN CAPITAL LETTER D */
        E                              = 0x0045,  /* U+0045 LATIN CAPITAL LETTER E */
        F                              = 0x0046,  /* U+0046 LATIN CAPITAL LETTER F */
        G                              = 0x0047,  /* U+0047 LATIN CAPITAL LETTER G */
        H                              = 0x0048,  /* U+0048 LATIN CAPITAL LETTER H */
        I                              = 0x0049,  /* U+0049 LATIN CAPITAL LETTER I */
        J                              = 0x004a,  /* U+004A LATIN CAPITAL LETTER J */
        K                              = 0x004b,  /* U+004B LATIN CAPITAL LETTER K */
        L                              = 0x004c,  /* U+004C LATIN CAPITAL LETTER L */
        M                              = 0x004d,  /* U+004D LATIN CAPITAL LETTER M */
        N                              = 0x004e,  /* U+004E LATIN CAPITAL LETTER N */
        O                              = 0x004f,  /* U+004F LATIN CAPITAL LETTER O */
        P                              = 0x0050,  /* U+0050 LATIN CAPITAL LETTER P */
        Q                              = 0x0051,  /* U+0051 LATIN CAPITAL LETTER Q */
        R                              = 0x0052,  /* U+0052 LATIN CAPITAL LETTER R */
        S                              = 0x0053,  /* U+0053 LATIN CAPITAL LETTER S */
        T                              = 0x0054,  /* U+0054 LATIN CAPITAL LETTER T */
        U                              = 0x0055,  /* U+0055 LATIN CAPITAL LETTER U */
        V                              = 0x0056,  /* U+0056 LATIN CAPITAL LETTER V */
        W                              = 0x0057,  /* U+0057 LATIN CAPITAL LETTER W */
        X                              = 0x0058,  /* U+0058 LATIN CAPITAL LETTER X */
        Y                              = 0x0059,  /* U+0059 LATIN CAPITAL LETTER Y */
        Z                              = 0x005a,  /* U+005A LATIN CAPITAL LETTER Z */
        bracketleft                    = 0x005b,  /* U+005B LEFT SQUARE BRACKET */
        backslash                      = 0x005c,  /* U+005C REVERSE SOLIDUS */
        bracketright                   = 0x005d,  /* U+005D RIGHT SQUARE BRACKET */
        asciicircum                    = 0x005e,  /* U+005E CIRCUMFLEX ACCENT */
        underscore                     = 0x005f,  /* U+005F LOW LINE */
        grave                          = 0x0060,  /* U+0060 GRAVE ACCENT */
        quoteleft                      = 0x0060,  /* deprecated */
        a                              = 0x0061,  /* U+0061 LATIN SMALL LETTER A */
        b                              = 0x0062,  /* U+0062 LATIN SMALL LETTER B */
        c                              = 0x0063,  /* U+0063 LATIN SMALL LETTER C */
        d                              = 0x0064,  /* U+0064 LATIN SMALL LETTER D */
        e                              = 0x0065,  /* U+0065 LATIN SMALL LETTER E */
        f                              = 0x0066,  /* U+0066 LATIN SMALL LETTER F */
        g                              = 0x0067,  /* U+0067 LATIN SMALL LETTER G */
        h                              = 0x0068,  /* U+0068 LATIN SMALL LETTER H */
        i                              = 0x0069,  /* U+0069 LATIN SMALL LETTER I */
        j                              = 0x006a,  /* U+006A LATIN SMALL LETTER J */
        k                              = 0x006b,  /* U+006B LATIN SMALL LETTER K */
        l                              = 0x006c,  /* U+006C LATIN SMALL LETTER L */
        m                              = 0x006d,  /* U+006D LATIN SMALL LETTER M */
        n                              = 0x006e,  /* U+006E LATIN SMALL LETTER N */
        o                              = 0x006f,  /* U+006F LATIN SMALL LETTER O */
        p                              = 0x0070,  /* U+0070 LATIN SMALL LETTER P */
        q                              = 0x0071,  /* U+0071 LATIN SMALL LETTER Q */
        r                              = 0x0072,  /* U+0072 LATIN SMALL LETTER R */
        s                              = 0x0073,  /* U+0073 LATIN SMALL LETTER S */
        t                              = 0x0074,  /* U+0074 LATIN SMALL LETTER T */
        u                              = 0x0075,  /* U+0075 LATIN SMALL LETTER U */
        v                              = 0x0076,  /* U+0076 LATIN SMALL LETTER V */
        w                              = 0x0077,  /* U+0077 LATIN SMALL LETTER W */
        x                              = 0x0078,  /* U+0078 LATIN SMALL LETTER X */
        y                              = 0x0079,  /* U+0079 LATIN SMALL LETTER Y */
        z                              = 0x007a,  /* U+007A LATIN SMALL LETTER Z */
        braceleft                      = 0x007b,  /* U+007B LEFT CURLY BRACKET */
        bar                            = 0x007c,  /* U+007C VERTICAL LINE */
        braceright                     = 0x007d,  /* U+007D RIGHT CURLY BRACKET */
        asciitilde                     = 0x007e,  /* U+007E TILDE */
        nobreakspace                   = 0x00a0,  /* U+00A0 NO-BREAK SPACE */
        exclamdown                     = 0x00a1,  /* U+00A1 INVERTED EXCLAMATION MARK */
        cent                           = 0x00a2,  /* U+00A2 CENT SIGN */
        sterling                       = 0x00a3,  /* U+00A3 POUND SIGN */
        currency                       = 0x00a4,  /* U+00A4 CURRENCY SIGN */
        yen                            = 0x00a5,  /* U+00A5 YEN SIGN */
        brokenbar                      = 0x00a6,  /* U+00A6 BROKEN BAR */
        section                        = 0x00a7,  /* U+00A7 SECTION SIGN */
        diaeresis                      = 0x00a8,  /* U+00A8 DIAERESIS */
        copyright                      = 0x00a9,  /* U+00A9 COPYRIGHT SIGN */
        ordfeminine                    = 0x00aa,  /* U+00AA FEMININE ORDINAL INDICATOR */
        guillemetleft                  = 0x00ab,  /* U+00AB LEFT-POINTING DOUBLE ANGLE QUOTATION MARK */
        guillemotleft                  = 0x00ab,  /* deprecated misspelling */
        notsign                        = 0x00ac,  /* U+00AC NOT SIGN */
        hyphen                         = 0x00ad,  /* U+00AD SOFT HYPHEN */
        registered                     = 0x00ae,  /* U+00AE REGISTERED SIGN */
        macron                         = 0x00af,  /* U+00AF MACRON */
        degree                         = 0x00b0,  /* U+00B0 DEGREE SIGN */
        plusminus                      = 0x00b1,  /* U+00B1 PLUS-MINUS SIGN */
        twosuperior                    = 0x00b2,  /* U+00B2 SUPERSCRIPT TWO */
        threesuperior                  = 0x00b3,  /* U+00B3 SUPERSCRIPT THREE */
        acute                          = 0x00b4,  /* U+00B4 ACUTE ACCENT */
        mu                             = 0x00b5,  /* U+00B5 MICRO SIGN */
        paragraph                      = 0x00b6,  /* U+00B6 PILCROW SIGN */
        periodcentered                 = 0x00b7,  /* U+00B7 MIDDLE DOT */
        cedilla                        = 0x00b8,  /* U+00B8 CEDILLA */
        onesuperior                    = 0x00b9,  /* U+00B9 SUPERSCRIPT ONE */
        ordmasculine                   = 0x00ba,  /* U+00BA MASCULINE ORDINAL INDICATOR */
        masculine                      = 0x00ba,  /* deprecated inconsistent name */
        guillemetright                 = 0x00bb,  /* U+00BB RIGHT-POINTING DOUBLE ANGLE QUOTATION MARK */
        guillemotright                 = 0x00bb,  /* deprecated misspelling */
        onequarter                     = 0x00bc,  /* U+00BC VULGAR FRACTION ONE QUARTER */
        onehalf                        = 0x00bd,  /* U+00BD VULGAR FRACTION ONE HALF */
        threequarters                  = 0x00be,  /* U+00BE VULGAR FRACTION THREE QUARTERS */
        questiondown                   = 0x00bf,  /* U+00BF INVERTED QUESTION MARK */
        Agrave                         = 0x00c0,  /* U+00C0 LATIN CAPITAL LETTER A WITH GRAVE */
        Aacute                         = 0x00c1,  /* U+00C1 LATIN CAPITAL LETTER A WITH ACUTE */
        Acircumflex                    = 0x00c2,  /* U+00C2 LATIN CAPITAL LETTER A WITH CIRCUMFLEX */
        Atilde                         = 0x00c3,  /* U+00C3 LATIN CAPITAL LETTER A WITH TILDE */
        Adiaeresis                     = 0x00c4,  /* U+00C4 LATIN CAPITAL LETTER A WITH DIAERESIS */
        Aring                          = 0x00c5,  /* U+00C5 LATIN CAPITAL LETTER A WITH RING ABOVE */
        AE                             = 0x00c6,  /* U+00C6 LATIN CAPITAL LETTER AE */
        Ccedilla                       = 0x00c7,  /* U+00C7 LATIN CAPITAL LETTER C WITH CEDILLA */
        Egrave                         = 0x00c8,  /* U+00C8 LATIN CAPITAL LETTER E WITH GRAVE */
        Eacute                         = 0x00c9,  /* U+00C9 LATIN CAPITAL LETTER E WITH ACUTE */
        Ecircumflex                    = 0x00ca,  /* U+00CA LATIN CAPITAL LETTER E WITH CIRCUMFLEX */
        Ediaeresis                     = 0x00cb,  /* U+00CB LATIN CAPITAL LETTER E WITH DIAERESIS */
        Igrave                         = 0x00cc,  /* U+00CC LATIN CAPITAL LETTER I WITH GRAVE */
        Iacute                         = 0x00cd,  /* U+00CD LATIN CAPITAL LETTER I WITH ACUTE */
        Icircumflex                    = 0x00ce,  /* U+00CE LATIN CAPITAL LETTER I WITH CIRCUMFLEX */
        Idiaeresis                     = 0x00cf,  /* U+00CF LATIN CAPITAL LETTER I WITH DIAERESIS */
        ETH                            = 0x00d0,  /* U+00D0 LATIN CAPITAL LETTER ETH */
        Eth                            = 0x00d0,  /* deprecated */
        Ntilde                         = 0x00d1,  /* U+00D1 LATIN CAPITAL LETTER N WITH TILDE */
        Ograve                         = 0x00d2,  /* U+00D2 LATIN CAPITAL LETTER O WITH GRAVE */
        Oacute                         = 0x00d3,  /* U+00D3 LATIN CAPITAL LETTER O WITH ACUTE */
        Ocircumflex                    = 0x00d4,  /* U+00D4 LATIN CAPITAL LETTER O WITH CIRCUMFLEX */
        Otilde                         = 0x00d5,  /* U+00D5 LATIN CAPITAL LETTER O WITH TILDE */
        Odiaeresis                     = 0x00d6,  /* U+00D6 LATIN CAPITAL LETTER O WITH DIAERESIS */
        multiply                       = 0x00d7,  /* U+00D7 MULTIPLICATION SIGN */
        Oslash                         = 0x00d8,  /* U+00D8 LATIN CAPITAL LETTER O WITH STROKE */
        Ooblique                       = 0x00d8,  /* deprecated alias for Oslash */
        Ugrave                         = 0x00d9,  /* U+00D9 LATIN CAPITAL LETTER U WITH GRAVE */
        Uacute                         = 0x00da,  /* U+00DA LATIN CAPITAL LETTER U WITH ACUTE */
        Ucircumflex                    = 0x00db,  /* U+00DB LATIN CAPITAL LETTER U WITH CIRCUMFLEX */
        Udiaeresis                     = 0x00dc,  /* U+00DC LATIN CAPITAL LETTER U WITH DIAERESIS */
        Yacute                         = 0x00dd,  /* U+00DD LATIN CAPITAL LETTER Y WITH ACUTE */
        THORN                          = 0x00de,  /* U+00DE LATIN CAPITAL LETTER THORN */
        Thorn                          = 0x00de,  /* deprecated */
        ssharp                         = 0x00df,  /* U+00DF LATIN SMALL LETTER SHARP S */
        agrave                         = 0x00e0,  /* U+00E0 LATIN SMALL LETTER A WITH GRAVE */
        aacute                         = 0x00e1,  /* U+00E1 LATIN SMALL LETTER A WITH ACUTE */
        acircumflex                    = 0x00e2,  /* U+00E2 LATIN SMALL LETTER A WITH CIRCUMFLEX */
        atilde                         = 0x00e3,  /* U+00E3 LATIN SMALL LETTER A WITH TILDE */
        adiaeresis                     = 0x00e4,  /* U+00E4 LATIN SMALL LETTER A WITH DIAERESIS */
        aring                          = 0x00e5,  /* U+00E5 LATIN SMALL LETTER A WITH RING ABOVE */
        ae                             = 0x00e6,  /* U+00E6 LATIN SMALL LETTER AE */
        ccedilla                       = 0x00e7,  /* U+00E7 LATIN SMALL LETTER C WITH CEDILLA */
        egrave                         = 0x00e8,  /* U+00E8 LATIN SMALL LETTER E WITH GRAVE */
        eacute                         = 0x00e9,  /* U+00E9 LATIN SMALL LETTER E WITH ACUTE */
        ecircumflex                    = 0x00ea,  /* U+00EA LATIN SMALL LETTER E WITH CIRCUMFLEX */
        ediaeresis                     = 0x00eb,  /* U+00EB LATIN SMALL LETTER E WITH DIAERESIS */
        igrave                         = 0x00ec,  /* U+00EC LATIN SMALL LETTER I WITH GRAVE */
        iacute                         = 0x00ed,  /* U+00ED LATIN SMALL LETTER I WITH ACUTE */
        icircumflex                    = 0x00ee,  /* U+00EE LATIN SMALL LETTER I WITH CIRCUMFLEX */
        idiaeresis                     = 0x00ef,  /* U+00EF LATIN SMALL LETTER I WITH DIAERESIS */
        eth                            = 0x00f0,  /* U+00F0 LATIN SMALL LETTER ETH */
        ntilde                         = 0x00f1,  /* U+00F1 LATIN SMALL LETTER N WITH TILDE */
        ograve                         = 0x00f2,  /* U+00F2 LATIN SMALL LETTER O WITH GRAVE */
        oacute                         = 0x00f3,  /* U+00F3 LATIN SMALL LETTER O WITH ACUTE */
        ocircumflex                    = 0x00f4,  /* U+00F4 LATIN SMALL LETTER O WITH CIRCUMFLEX */
        otilde                         = 0x00f5,  /* U+00F5 LATIN SMALL LETTER O WITH TILDE */
        odiaeresis                     = 0x00f6,  /* U+00F6 LATIN SMALL LETTER O WITH DIAERESIS */
        division                       = 0x00f7,  /* U+00F7 DIVISION SIGN */
        oslash                         = 0x00f8,  /* U+00F8 LATIN SMALL LETTER O WITH STROKE */
        ooblique                       = 0x00f8,  /* deprecated alias for oslash */
        ugrave                         = 0x00f9,  /* U+00F9 LATIN SMALL LETTER U WITH GRAVE */
        uacute                         = 0x00fa,  /* U+00FA LATIN SMALL LETTER U WITH ACUTE */
        ucircumflex                    = 0x00fb,  /* U+00FB LATIN SMALL LETTER U WITH CIRCUMFLEX */
        udiaeresis                     = 0x00fc,  /* U+00FC LATIN SMALL LETTER U WITH DIAERESIS */
        yacute                         = 0x00fd,  /* U+00FD LATIN SMALL LETTER Y WITH ACUTE */
        thorn                          = 0x00fe,  /* U+00FE LATIN SMALL LETTER THORN */
        ydiaeresis                     = 0x00ff,  /* U+00FF LATIN SMALL LETTER Y WITH DIAERESIS */
        Aogonek                        = 0x01a1,  /* U+0104 LATIN CAPITAL LETTER A WITH OGONEK */
        breve                          = 0x01a2,  /* U+02D8 BREVE */
        Lstroke                        = 0x01a3,  /* U+0141 LATIN CAPITAL LETTER L WITH STROKE */
        Lcaron                         = 0x01a5,  /* U+013D LATIN CAPITAL LETTER L WITH CARON */
        Sacute                         = 0x01a6,  /* U+015A LATIN CAPITAL LETTER S WITH ACUTE */
        Scaron                         = 0x01a9,  /* U+0160 LATIN CAPITAL LETTER S WITH CARON */
        Scedilla                       = 0x01aa,  /* U+015E LATIN CAPITAL LETTER S WITH CEDILLA */
        Tcaron                         = 0x01ab,  /* U+0164 LATIN CAPITAL LETTER T WITH CARON */
        Zacute                         = 0x01ac,  /* U+0179 LATIN CAPITAL LETTER Z WITH ACUTE */
        Zcaron                         = 0x01ae,  /* U+017D LATIN CAPITAL LETTER Z WITH CARON */
        Zabovedot                      = 0x01af,  /* U+017B LATIN CAPITAL LETTER Z WITH DOT ABOVE */
        aogonek                        = 0x01b1,  /* U+0105 LATIN SMALL LETTER A WITH OGONEK */
        ogonek                         = 0x01b2,  /* U+02DB OGONEK */
        lstroke                        = 0x01b3,  /* U+0142 LATIN SMALL LETTER L WITH STROKE */
        lcaron                         = 0x01b5,  /* U+013E LATIN SMALL LETTER L WITH CARON */
        sacute                         = 0x01b6,  /* U+015B LATIN SMALL LETTER S WITH ACUTE */
        caron                          = 0x01b7,  /* U+02C7 CARON */
        scaron                         = 0x01b9,  /* U+0161 LATIN SMALL LETTER S WITH CARON */
        scedilla                       = 0x01ba,  /* U+015F LATIN SMALL LETTER S WITH CEDILLA */
        tcaron                         = 0x01bb,  /* U+0165 LATIN SMALL LETTER T WITH CARON */
        zacute                         = 0x01bc,  /* U+017A LATIN SMALL LETTER Z WITH ACUTE */
        doubleacute                    = 0x01bd,  /* U+02DD DOUBLE ACUTE ACCENT */
        zcaron                         = 0x01be,  /* U+017E LATIN SMALL LETTER Z WITH CARON */
        zabovedot                      = 0x01bf,  /* U+017C LATIN SMALL LETTER Z WITH DOT ABOVE */
        Racute                         = 0x01c0,  /* U+0154 LATIN CAPITAL LETTER R WITH ACUTE */
        Abreve                         = 0x01c3,  /* U+0102 LATIN CAPITAL LETTER A WITH BREVE */
        Lacute                         = 0x01c5,  /* U+0139 LATIN CAPITAL LETTER L WITH ACUTE */
        Cacute                         = 0x01c6,  /* U+0106 LATIN CAPITAL LETTER C WITH ACUTE */
        Ccaron                         = 0x01c8,  /* U+010C LATIN CAPITAL LETTER C WITH CARON */
        Eogonek                        = 0x01ca,  /* U+0118 LATIN CAPITAL LETTER E WITH OGONEK */
        Ecaron                         = 0x01cc,  /* U+011A LATIN CAPITAL LETTER E WITH CARON */
        Dcaron                         = 0x01cf,  /* U+010E LATIN CAPITAL LETTER D WITH CARON */
        Dstroke                        = 0x01d0,  /* U+0110 LATIN CAPITAL LETTER D WITH STROKE */
        Nacute                         = 0x01d1,  /* U+0143 LATIN CAPITAL LETTER N WITH ACUTE */
        Ncaron                         = 0x01d2,  /* U+0147 LATIN CAPITAL LETTER N WITH CARON */
        Odoubleacute                   = 0x01d5,  /* U+0150 LATIN CAPITAL LETTER O WITH DOUBLE ACUTE */
        Rcaron                         = 0x01d8,  /* U+0158 LATIN CAPITAL LETTER R WITH CARON */
        Uring                          = 0x01d9,  /* U+016E LATIN CAPITAL LETTER U WITH RING ABOVE */
        Udoubleacute                   = 0x01db,  /* U+0170 LATIN CAPITAL LETTER U WITH DOUBLE ACUTE */
        Tcedilla                       = 0x01de,  /* U+0162 LATIN CAPITAL LETTER T WITH CEDILLA */
        racute                         = 0x01e0,  /* U+0155 LATIN SMALL LETTER R WITH ACUTE */
        abreve                         = 0x01e3,  /* U+0103 LATIN SMALL LETTER A WITH BREVE */
        lacute                         = 0x01e5,  /* U+013A LATIN SMALL LETTER L WITH ACUTE */
        cacute                         = 0x01e6,  /* U+0107 LATIN SMALL LETTER C WITH ACUTE */
        ccaron                         = 0x01e8,  /* U+010D LATIN SMALL LETTER C WITH CARON */
        eogonek                        = 0x01ea,  /* U+0119 LATIN SMALL LETTER E WITH OGONEK */
        ecaron                         = 0x01ec,  /* U+011B LATIN SMALL LETTER E WITH CARON */
        dcaron                         = 0x01ef,  /* U+010F LATIN SMALL LETTER D WITH CARON */
        dstroke                        = 0x01f0,  /* U+0111 LATIN SMALL LETTER D WITH STROKE */
        nacute                         = 0x01f1,  /* U+0144 LATIN SMALL LETTER N WITH ACUTE */
        ncaron                         = 0x01f2,  /* U+0148 LATIN SMALL LETTER N WITH CARON */
        odoubleacute                   = 0x01f5,  /* U+0151 LATIN SMALL LETTER O WITH DOUBLE ACUTE */
        rcaron                         = 0x01f8,  /* U+0159 LATIN SMALL LETTER R WITH CARON */
        uring                          = 0x01f9,  /* U+016F LATIN SMALL LETTER U WITH RING ABOVE */
        udoubleacute                   = 0x01fb,  /* U+0171 LATIN SMALL LETTER U WITH DOUBLE ACUTE */
        tcedilla                       = 0x01fe,  /* U+0163 LATIN SMALL LETTER T WITH CEDILLA */
        abovedot                       = 0x01ff,  /* U+02D9 DOT ABOVE */
        Hstroke                        = 0x02a1,  /* U+0126 LATIN CAPITAL LETTER H WITH STROKE */
        Hcircumflex                    = 0x02a6,  /* U+0124 LATIN CAPITAL LETTER H WITH CIRCUMFLEX */
        Iabovedot                      = 0x02a9,  /* U+0130 LATIN CAPITAL LETTER I WITH DOT ABOVE */
        Gbreve                         = 0x02ab,  /* U+011E LATIN CAPITAL LETTER G WITH BREVE */
        Jcircumflex                    = 0x02ac,  /* U+0134 LATIN CAPITAL LETTER J WITH CIRCUMFLEX */
        hstroke                        = 0x02b1,  /* U+0127 LATIN SMALL LETTER H WITH STROKE */
        hcircumflex                    = 0x02b6,  /* U+0125 LATIN SMALL LETTER H WITH CIRCUMFLEX */
        idotless                       = 0x02b9,  /* U+0131 LATIN SMALL LETTER DOTLESS I */
        gbreve                         = 0x02bb,  /* U+011F LATIN SMALL LETTER G WITH BREVE */
        jcircumflex                    = 0x02bc,  /* U+0135 LATIN SMALL LETTER J WITH CIRCUMFLEX */
        Cabovedot                      = 0x02c5,  /* U+010A LATIN CAPITAL LETTER C WITH DOT ABOVE */
        Ccircumflex                    = 0x02c6,  /* U+0108 LATIN CAPITAL LETTER C WITH CIRCUMFLEX */
        Gabovedot                      = 0x02d5,  /* U+0120 LATIN CAPITAL LETTER G WITH DOT ABOVE */
        Gcircumflex                    = 0x02d8,  /* U+011C LATIN CAPITAL LETTER G WITH CIRCUMFLEX */
        Ubreve                         = 0x02dd,  /* U+016C LATIN CAPITAL LETTER U WITH BREVE */
        Scircumflex                    = 0x02de,  /* U+015C LATIN CAPITAL LETTER S WITH CIRCUMFLEX */
        cabovedot                      = 0x02e5,  /* U+010B LATIN SMALL LETTER C WITH DOT ABOVE */
        ccircumflex                    = 0x02e6,  /* U+0109 LATIN SMALL LETTER C WITH CIRCUMFLEX */
        gabovedot                      = 0x02f5,  /* U+0121 LATIN SMALL LETTER G WITH DOT ABOVE */
        gcircumflex                    = 0x02f8,  /* U+011D LATIN SMALL LETTER G WITH CIRCUMFLEX */
        ubreve                         = 0x02fd,  /* U+016D LATIN SMALL LETTER U WITH BREVE */
        scircumflex                    = 0x02fe,  /* U+015D LATIN SMALL LETTER S WITH CIRCUMFLEX */
        kra                            = 0x03a2,  /* U+0138 LATIN SMALL LETTER KRA */
        kappa                          = 0x03a2,  /* deprecated */
        Rcedilla                       = 0x03a3,  /* U+0156 LATIN CAPITAL LETTER R WITH CEDILLA */
        Itilde                         = 0x03a5,  /* U+0128 LATIN CAPITAL LETTER I WITH TILDE */
        Lcedilla                       = 0x03a6,  /* U+013B LATIN CAPITAL LETTER L WITH CEDILLA */
        Emacron                        = 0x03aa,  /* U+0112 LATIN CAPITAL LETTER E WITH MACRON */
        Gcedilla                       = 0x03ab,  /* U+0122 LATIN CAPITAL LETTER G WITH CEDILLA */
        Tslash                         = 0x03ac,  /* U+0166 LATIN CAPITAL LETTER T WITH STROKE */
        rcedilla                       = 0x03b3,  /* U+0157 LATIN SMALL LETTER R WITH CEDILLA */
        itilde                         = 0x03b5,  /* U+0129 LATIN SMALL LETTER I WITH TILDE */
        lcedilla                       = 0x03b6,  /* U+013C LATIN SMALL LETTER L WITH CEDILLA */
        emacron                        = 0x03ba,  /* U+0113 LATIN SMALL LETTER E WITH MACRON */
        gcedilla                       = 0x03bb,  /* U+0123 LATIN SMALL LETTER G WITH CEDILLA */
        tslash                         = 0x03bc,  /* U+0167 LATIN SMALL LETTER T WITH STROKE */
        ENG                            = 0x03bd,  /* U+014A LATIN CAPITAL LETTER ENG */
        eng                            = 0x03bf,  /* U+014B LATIN SMALL LETTER ENG */
        Amacron                        = 0x03c0,  /* U+0100 LATIN CAPITAL LETTER A WITH MACRON */
        Iogonek                        = 0x03c7,  /* U+012E LATIN CAPITAL LETTER I WITH OGONEK */
        Eabovedot                      = 0x03cc,  /* U+0116 LATIN CAPITAL LETTER E WITH DOT ABOVE */
        Imacron                        = 0x03cf,  /* U+012A LATIN CAPITAL LETTER I WITH MACRON */
        Ncedilla                       = 0x03d1,  /* U+0145 LATIN CAPITAL LETTER N WITH CEDILLA */
        Omacron                        = 0x03d2,  /* U+014C LATIN CAPITAL LETTER O WITH MACRON */
        Kcedilla                       = 0x03d3,  /* U+0136 LATIN CAPITAL LETTER K WITH CEDILLA */
        Uogonek                        = 0x03d9,  /* U+0172 LATIN CAPITAL LETTER U WITH OGONEK */
        Utilde                         = 0x03dd,  /* U+0168 LATIN CAPITAL LETTER U WITH TILDE */
        Umacron                        = 0x03de,  /* U+016A LATIN CAPITAL LETTER U WITH MACRON */
        amacron                        = 0x03e0,  /* U+0101 LATIN SMALL LETTER A WITH MACRON */
        iogonek                        = 0x03e7,  /* U+012F LATIN SMALL LETTER I WITH OGONEK */
        eabovedot                      = 0x03ec,  /* U+0117 LATIN SMALL LETTER E WITH DOT ABOVE */
        imacron                        = 0x03ef,  /* U+012B LATIN SMALL LETTER I WITH MACRON */
        ncedilla                       = 0x03f1,  /* U+0146 LATIN SMALL LETTER N WITH CEDILLA */
        omacron                        = 0x03f2,  /* U+014D LATIN SMALL LETTER O WITH MACRON */
        kcedilla                       = 0x03f3,  /* U+0137 LATIN SMALL LETTER K WITH CEDILLA */
        uogonek                        = 0x03f9,  /* U+0173 LATIN SMALL LETTER U WITH OGONEK */
        utilde                         = 0x03fd,  /* U+0169 LATIN SMALL LETTER U WITH TILDE */
        umacron                        = 0x03fe,  /* U+016B LATIN SMALL LETTER U WITH MACRON */
        Wcircumflex                    = 0x1000174,  /* U+0174 LATIN CAPITAL LETTER W WITH CIRCUMFLEX */
        wcircumflex                    = 0x1000175,  /* U+0175 LATIN SMALL LETTER W WITH CIRCUMFLEX */
        Ycircumflex                    = 0x1000176,  /* U+0176 LATIN CAPITAL LETTER Y WITH CIRCUMFLEX */
        ycircumflex                    = 0x1000177,  /* U+0177 LATIN SMALL LETTER Y WITH CIRCUMFLEX */
        Babovedot                      = 0x1001e02,  /* U+1E02 LATIN CAPITAL LETTER B WITH DOT ABOVE */
        babovedot                      = 0x1001e03,  /* U+1E03 LATIN SMALL LETTER B WITH DOT ABOVE */
        Dabovedot                      = 0x1001e0a,  /* U+1E0A LATIN CAPITAL LETTER D WITH DOT ABOVE */
        dabovedot                      = 0x1001e0b,  /* U+1E0B LATIN SMALL LETTER D WITH DOT ABOVE */
        Fabovedot                      = 0x1001e1e,  /* U+1E1E LATIN CAPITAL LETTER F WITH DOT ABOVE */
        fabovedot                      = 0x1001e1f,  /* U+1E1F LATIN SMALL LETTER F WITH DOT ABOVE */
        Mabovedot                      = 0x1001e40,  /* U+1E40 LATIN CAPITAL LETTER M WITH DOT ABOVE */
        mabovedot                      = 0x1001e41,  /* U+1E41 LATIN SMALL LETTER M WITH DOT ABOVE */
        Pabovedot                      = 0x1001e56,  /* U+1E56 LATIN CAPITAL LETTER P WITH DOT ABOVE */
        pabovedot                      = 0x1001e57,  /* U+1E57 LATIN SMALL LETTER P WITH DOT ABOVE */
        Sabovedot                      = 0x1001e60,  /* U+1E60 LATIN CAPITAL LETTER S WITH DOT ABOVE */
        sabovedot                      = 0x1001e61,  /* U+1E61 LATIN SMALL LETTER S WITH DOT ABOVE */
        Tabovedot                      = 0x1001e6a,  /* U+1E6A LATIN CAPITAL LETTER T WITH DOT ABOVE */
        tabovedot                      = 0x1001e6b,  /* U+1E6B LATIN SMALL LETTER T WITH DOT ABOVE */
        Wgrave                         = 0x1001e80,  /* U+1E80 LATIN CAPITAL LETTER W WITH GRAVE */
        wgrave                         = 0x1001e81,  /* U+1E81 LATIN SMALL LETTER W WITH GRAVE */
        Wacute                         = 0x1001e82,  /* U+1E82 LATIN CAPITAL LETTER W WITH ACUTE */
        wacute                         = 0x1001e83,  /* U+1E83 LATIN SMALL LETTER W WITH ACUTE */
        Wdiaeresis                     = 0x1001e84,  /* U+1E84 LATIN CAPITAL LETTER W WITH DIAERESIS */
        wdiaeresis                     = 0x1001e85,  /* U+1E85 LATIN SMALL LETTER W WITH DIAERESIS */
        Ygrave                         = 0x1001ef2,  /* U+1EF2 LATIN CAPITAL LETTER Y WITH GRAVE */
        ygrave                         = 0x1001ef3  /* U+1EF3 LATIN SMALL LETTER Y WITH GRAVE */
    };
}
